name: Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:  
  jest:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
          
      - name: Install dependencies
        run: yarn
        
      - name: Jest tests
        run: yarn test
        
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
        
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14
          
      - name: Install dependencies
        run: yarn
      
      - name: Build
        run: yarn test-build
