name: Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:  
  Test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
        
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14
          
      - name: Install dependencies
        run: yarn
        
      - name: Test
        run: yarn test
        
      - name: Build
        run: yarn test-build
